apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-deployment
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart
          image: saileshk1103/sep2_shoppingcart_localization_assignment:latest
          command: ["java", "-Djava.awt.headless=false", "-jar", "app.jar"]
          env:
            - name: DB_HOST
              value: "db-service"
            - name: DB_NAME
              value: "shopping_cart_localization"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DISPLAY
              value: "host.docker.internal:0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6
          env:
            - name: MARIADB_DATABASE
              value: "shopping_cart_localization"
            - name: MYSQL_TCP_PORT
              value: "3307"
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          volumeMounts:
            - name: init-script-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script-volume
          configMap:
            name: mariadb-init-config
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: mariadb
  ports:
    - port: 3307
      targetPort: 3307