version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: shopping_cart_db
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD} # Using your pass for root too
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: saileshk1103/sep2_shoppingcart_localization_assignment:latest
    container_name: shopping_cart_app
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:mariadb://db:3306/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DISPLAY=docker.for.mac.host.internal:0
    privileged: true
    ports:
      - "8080:8080"